<?php

/**
 * @file
 * Installation file for the WinCacheDrupal module.
 */

/**
 * Implements hook_init().
 *
 * Used for displaying the WinCache stats for debug purposes.
 */
function wincachedrupal_init(&$page) {
  global $user;
  global $wincache_collect_statistics;
  $wincache_collect_statistics = false;
  
  if (($user->uid == 0) || !variable_get('wincache_show_debug', FALSE)
      || !user_access('access wincache statistics') || strstr($_SERVER['PHP_SELF'], 'update.php')
      || strstr($_GET['q'], 'autocomplete')) {
    return;
  }

  $wincache_collect_statistics = true;
  register_shutdown_function('wincachedrupal_shutdown');
}

/**
 * Implements hook_menu().
 */
function wincachedrupal_menu() {
  $items['admin/reports/status/wincache'] = array(
    'title' => 'Wincache',
    'page callback' => 'WincacheDrupalStatsPageCallback',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'wincachedrupal.inc',
  );
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function wincachedrupal_admin_paths() {
  $paths = array(
    // This page should not be treated as administrative since it outputs its
    // own content (outside of any administration theme).
    'admin/reports/status/wincache' => FALSE,
  );
  return $paths;
}

/**
 * Implements hook_permission().
 */
function wincachedrupal_permission() {
  return array(
    'access wincache statistics' => array(
      'title' => t('Access wincache statistics'),
      'description' => t('Allows access to the statistics reports of WinCache.'),
    ),
  );
}

/**
 * Shutdown function to render statistics.
 *
 * See wincache_init() which registers this function as a shutdown function.
 * Displays apc stats in the footer.
 */
function wincachedrupal_shutdown() {
  global $wincache_statistics;

  // Try not to break non-HTML pages.
  if (strstr(drupal_get_html_head(), 'text/html') == FALSE) {
    return;
  }

  print '<div id="apc-devel"><h2>' . t('Wincache statistics') . '</h2>';
  $rows = array();
  foreach ($wincache_statistics as $row) {
    $row[2] = implode(',<br />', $row[2]);
    $rows[] = $row;
  }
  print theme('table', array(
    'header' => array(('Type'), t('Bin'), t('Cid(s)')),
    'rows' => $rows,
  ));
  print '</div>';
}
